# Generated by Django 2.0.4 on 2019-11-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('start', models.DateTimeField(verbose_name='上班打卡时间')),
                ('end', models.DateTimeField(verbose_name='下班打卡时间')),
                ('statu', models.IntegerField(choices=[(1, '迟到'), (2, '早退'), (3, '缺勤'), (4, '正常')], verbose_name='打卡状态')),
            ],
            options={
                'verbose_name': '考勤',
                'verbose_name_plural': '考勤',
                'db_table': 'checking',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='基础工资')),
                ('dividend', models.IntegerField(blank=True, choices=[(1, '3000'), (2, '5000'), (3, '8000')], null=True, verbose_name='奖金')),
                ('wage', models.IntegerField(blank=True, null=True, verbose_name='加班时薪')),
                ('start', models.TimeField(blank=True, null=True, verbose_name='上班打卡时间')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='下班打卡时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ln.Department', verbose_name='父类架构')),
            ],
            options={
                'verbose_name': '组织架构',
                'verbose_name_plural': '组织架构',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Evection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('destination', models.CharField(max_length=200, verbose_name='目的地')),
                ('start', models.DateTimeField(verbose_name='出差日期')),
                ('end', models.DateTimeField(verbose_name='结束出差日期')),
                ('num', models.IntegerField(verbose_name='出差天数')),
                ('reason', models.TextField(verbose_name='出差事由')),
                ('result', models.IntegerField(choices=[(1, '拒绝'), (2, '通过'), (3, '等待中')], default=3, verbose_name='审批状态')),
                ('command', models.TextField(blank=True, null=True, verbose_name='审核结果的批示')),
            ],
            options={
                'verbose_name': '出差',
                'verbose_name_plural': '出差',
                'db_table': 'evection',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('leave_type', models.IntegerField(choices=[(1, '事假'), (2, '病假'), (3, '年假')], verbose_name='请假类型')),
                ('start', models.DateTimeField(verbose_name='请假日期')),
                ('end', models.DateTimeField(verbose_name='结束日期')),
                ('num', models.IntegerField(verbose_name='请假天数')),
                ('reason', models.TextField(verbose_name='请假事由')),
                ('result', models.IntegerField(choices=[(1, '拒绝'), (2, '通过'), (3, '等待中')], default=3, verbose_name='审批状态')),
                ('command', models.TextField(blank=True, null=True, verbose_name='审核结果的批示')),
            ],
            options={
                'verbose_name': '请假',
                'verbose_name_plural': '请假',
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('log_type', models.IntegerField(choices=[(1, '日报'), (2, '周报'), (3, '月报')], verbose_name='日志类型')),
                ('work', models.TextField(verbose_name='今日工作')),
                ('unfinished', models.TextField(verbose_name='未完成工作')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('start', models.DateTimeField(verbose_name='加班日期时间')),
                ('end', models.DateTimeField(verbose_name='结束日期时间')),
                ('num', models.IntegerField(verbose_name='加班时长')),
                ('reason', models.TextField(verbose_name='加班事由')),
                ('result', models.IntegerField(choices=[(1, '拒绝'), (2, '通过'), (3, '等待中')], default=3, verbose_name='审批状态')),
                ('command', models.TextField(blank=True, null=True, verbose_name='审核结果的批示')),
            ],
            options={
                'verbose_name': '加班',
                'verbose_name_plural': '加班',
                'db_table': 'overtime',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('overtime', models.IntegerField(blank=True, null=True, verbose_name='加班时长')),
                ('delgold', models.IntegerField(blank=True, null=True, verbose_name='扣除金额')),
                ('overmoney', models.IntegerField(blank=True, null=True, verbose_name='额外奖金或提成')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salarydepartment', to='ln.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '薪资',
                'verbose_name_plural': '薪资',
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('password', models.CharField(default='123456', max_length=200, verbose_name='密码')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('position', models.IntegerField(blank=True, choices=[(1, '普通员工'), (2, '经理'), (3, '科长'), (4, '部长'), (5, '总监'), (6, '管理层'), (7, '高级管理者'), (8, '总经理')], null=True, verbose_name='职位')),
                ('number', models.CharField(max_length=200, unique=True, verbose_name='工号')),
                ('image', models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media/%Y/%m', verbose_name='头像')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ln.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaryuser', to='ln.User', verbose_name='所属员工'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='approve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtimeapprove', to='ln.User', verbose_name='假条审批人'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtimeinitiator', to='ln.User', verbose_name='假条发起人'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtimeleader', to='ln.User', verbose_name='抄送人'),
        ),
        migrations.AddField(
            model_name='log',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loginitiator', to='ln.User', verbose_name='日志发出人'),
        ),
        migrations.AddField(
            model_name='log',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logleader', to='ln.User', verbose_name='抄送人'),
        ),
        migrations.AddField(
            model_name='leave',
            name='approve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveapprove', to='ln.User', verbose_name='假条审批人'),
        ),
        migrations.AddField(
            model_name='leave',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveinitiator', to='ln.User', verbose_name='假条发起人'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveleader', to='ln.User', verbose_name='抄送人'),
        ),
        migrations.AddField(
            model_name='evection',
            name='approve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evectionapprove', to='ln.User', verbose_name='出差审批人'),
        ),
        migrations.AddField(
            model_name='evection',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evectioninitiator', to='ln.User', verbose_name='出差发起人'),
        ),
        migrations.AddField(
            model_name='evection',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evectionleader', to='ln.User', verbose_name='抄送人'),
        ),
        migrations.AddField(
            model_name='checking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ln.User', verbose_name='关联员工'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcementdepartment', to='ln.Department'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcementuser', to='ln.User', verbose_name='公告发起人'),
        ),
        migrations.AlterUniqueTogether(
            name='overtime',
            unique_together={('initiator', 'approve', 'leader')},
        ),
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together={('initiator', 'approve', 'leader')},
        ),
        migrations.AlterUniqueTogether(
            name='evection',
            unique_together={('initiator', 'approve', 'leader')},
        ),
    ]
