# Generated by Django 2.0.4 on 2019-11-21 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='更改时间'),
        ),
    ]
