# Generated by Django 2.0.4 on 2019-11-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0003_permission_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='code',
        ),
    ]
