# Generated by Django 2.0.4 on 2019-11-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0004_remove_permission_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='department',
        ),
    ]
