# Generated by Django 2.0.4 on 2019-11-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0006_auto_20191125_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='ln.Role', verbose_name='员工拥有的角色'),
        ),
    ]
