# Generated by Django 2.0.4 on 2019-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0007_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='leader',
        ),
        migrations.AddField(
            model_name='log',
            name='leader',
            field=models.ManyToManyField(blank=True, related_name='logleader', to='ln.User', verbose_name='抄送人'),
        ),
        migrations.AlterUniqueTogether(
            name='evection',
            unique_together={('initiator', 'approve')},
        ),
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together={('initiator', 'approve')},
        ),
        migrations.AlterUniqueTogether(
            name='overtime',
            unique_together={('initiator', 'approve')},
        ),
    ]
