# Generated by Django 2.0.4 on 2019-11-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0008_auto_20191127_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depar', to='ln.Department', verbose_name='父类架构'),
        ),
        migrations.RemoveField(
            model_name='evection',
            name='leader',
        ),
        migrations.AddField(
            model_name='evection',
            name='leader',
            field=models.ManyToManyField(blank=True, related_name='evectionleader', to='ln.User', verbose_name='抄送人'),
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leader',
        ),
        migrations.AddField(
            model_name='leave',
            name='leader',
            field=models.ManyToManyField(blank=True, related_name='leaveleader', to='ln.User', verbose_name='抄送人'),
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='leader',
        ),
        migrations.AddField(
            model_name='overtime',
            name='leader',
            field=models.ManyToManyField(blank=True, related_name='overtimeleader', to='ln.User', verbose_name='抄送人'),
        ),
    ]
