# Generated by Django 2.0.4 on 2019-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0009_auto_20191127_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.IntegerField(choices=[(1, '事假'), (2, '病假')], verbose_name='请假类型'),
        ),
    ]
