# Generated by Django 2.0.4 on 2019-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0010_auto_20191128_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_roles', to='ln.Role', verbose_name='员工拥有的角色'),
        ),
    ]
