# Generated by Django 2.0.4 on 2019-11-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0011_auto_20191128_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together=set(),
        ),
    ]
